$(function(){
	$(document).on('click','#show-actions',function(){
		$.actions({
			title:'选择操作',
			onClose:function(){
				console.log('close');
			},
			actions:[
				{
					text:'发布',
					className:'color-primary',
					onClick:function(){
						$.alert('发布成功');
					}
				}
			]
		})
	});
	$(document).on('click','#show-actions-bg',function(){
		$.actions({
			title:'选择背景颜色',
			onClose:function(){
				console.log('close');
			},
			actions:[
				{
					text:'绿色',
					className:'bg-primary',
					onClick:function(){
						$(document.body).css('background','green');
					}
				},
				{
					text:'橙色',
					className:'bg-warning',
					onClick:function(){
						$(document.body).css('background','orange');
					}
				},
				{
					text:'红色',
					className:'bg-danger',
					onClick:function(){
						$(document.body).css('background','red');
					}
				}
			]
		});
	});
})